import useStore from '../store/useStore';

// Mapas de locale e moeda
const LOCALE_MAP = {
    'pt-BR': 'pt-BR',
    'en': 'en-US',
    'es': 'es-ES',
};

export const formatCurrency = (v) => {
    const currency = useStore.getState().currency || 'BRL';
    const language = useStore.getState().language || 'pt-BR';
    const locale = LOCALE_MAP[language] || 'pt-BR';
    return new Intl.NumberFormat(locale, { style: 'currency', currency }).format(v || 0);
};

export const formatDate = (d) => {
    const language = useStore.getState().language || 'pt-BR';
    const locale = LOCALE_MAP[language] || 'pt-BR';
    return new Date(d).toLocaleDateString(locale, { day: '2-digit', month: '2-digit', year: 'numeric' });
};

export const getCurrentMonth = () => {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
};

export const getPercentage = (current, total) =>
    total > 0 ? Math.round((current / total) * 100) : 0;

export const CATEGORY_COLORS = ['#00E676', '#FF5252', '#448AFF', '#FFD740', '#E040FB', '#FF6E40', '#18FFFF', '#B388FF', '#69F0AE', '#A0A0A0'];

export const CATEGORY_MAP = {
    alimentacao: { name: 'Alimentação', icon: 'UtensilsCrossed' },
    transporte: { name: 'Transporte', icon: 'Car' },
    moradia: { name: 'Moradia', icon: 'Home' },
    saude: { name: 'Saúde', icon: 'Heart' },
    lazer: { name: 'Lazer', icon: 'Gamepad2' },
    educacao: { name: 'Educação', icon: 'GraduationCap' },
    vestuario: { name: 'Vestuário', icon: 'Shirt' },
    tecnologia: { name: 'Tecnologia', icon: 'Smartphone' },
    outros: { name: 'Outros', icon: 'MoreHorizontal' },
    salario: { name: 'Salário', icon: 'DollarSign' },
    freelance: { name: 'Freelance', icon: 'Briefcase' },
    investimento: { name: 'Investimento', icon: 'TrendingUp' },
    presente: { name: 'Presente', icon: 'Gift' },
};

export const mapCategoryName = (suggestion) => {
    if (!suggestion) return 'outros';
    const lower = suggestion.toLowerCase().trim();
    const map = {
        'alimentação': 'alimentacao', 'comida': 'alimentacao', 'restaurante': 'alimentacao', 'mercado': 'alimentacao',
        'transporte': 'transporte', 'uber': 'transporte', 'combustível': 'transporte',
        'moradia': 'moradia', 'aluguel': 'moradia', 'energia': 'moradia', 'internet': 'moradia',
        'saúde': 'saude', 'farmácia': 'saude', 'médico': 'saude',
        'lazer': 'lazer', 'entretenimento': 'lazer', 'cinema': 'lazer',
        'educação': 'educacao', 'curso': 'educacao', 'escola': 'educacao',
        'vestuário': 'vestuario', 'roupa': 'vestuario',
        'tecnologia': 'tecnologia', 'celular': 'tecnologia',
        'salário': 'salario', 'freelance': 'freelance', 'investimento': 'investimento', 'presente': 'presente',
    };
    return map[lower] || CATEGORY_MAP[lower] ? lower : 'outros';
};

// ========== SISTEMA i18n COMPLETO ==========
const translations = {
    'pt-BR': {
        dashboard: 'Painel', transactions: 'Transações', add: 'Adicionar',
        budgets: 'Orçamentos', goals: 'Metas', reports: 'Relatórios',
        profile: 'Perfil', preferences: 'Preferências', security: 'Segurança',
        help: 'Ajuda & Suporte', paymentMethods: 'Métodos de Pagamento',
        investments: 'Investimentos', newTransaction: 'Nova Transação',
        welcomeBack: 'Bem-vindo de volta!', hi: 'Olá', overview: 'Visão Geral',
        totalBalance: 'Saldo Total', quickActions: 'Ações Rápidas',
        send: 'Enviar', receive: 'Receber', swap: 'Trocar', payBills: 'Pagar Conta',
        recentTransactions: 'Transações Recentes', seeAll: 'Ver Tudo',
        cardHolder: 'Titular', expireDate: 'Validade',
        incomeBreakdown: 'Análise de Receitas',
        allTransactions: 'Todas as Transações', searchTransactions: 'Buscar transações...',
        all: 'Todos', noTransactionsYet: 'Nenhuma transação ainda.', today: 'Hoje',
        addTransaction: 'Adicionar Transação', amount: 'Valor',
        description: 'Descrição', category: 'Categoria', date: 'Data',
        selectCategory: 'Selecione uma categoria', addDescription: 'Adicione uma descrição',
        creating: 'Criando...', create: 'Criar',
        income: 'Receita', expense: 'Despesa',
        spendSmart: 'Gaste com Sabedoria', noBudgets: 'Sem orçamentos',
        createBudget: 'Criar um orçamento para controlar seus gastos.',
        addBudget: 'Adicionar Orçamento', newBudget: 'Novo Orçamento',
        monthlyLimit: 'Limite Mensal', limitReached: 'do limite atingido', of: 'de',
        savings: 'Poupança', lifeGoals: 'Metas de Vida', noGoals: 'Sem metas definidas',
        whatSavingFor: 'Para o que você está guardando dinheiro?',
        createGoal: 'Criar Meta', newGoal: 'Nova Meta', goalName: 'Nome da Meta',
        targetAmount: 'Valor Alvo', targetDate: 'Data Alvo (Opcional)',
        saved2: 'Guardado', goal: 'Meta',
        analytics: 'Análises', overviewReports: 'Relatórios Gerais',
        totalIncome: 'Receita Total', totalExpense: 'Despesa Total',
        netBalance: 'Saldo Líquido', expenseByCategory: 'Despesas por Categoria',
        incomeVsExpense: 'Receitas vs Despesas', totalSpend: 'Total Gasto',
        noExpensesMonth: 'Sem despesas este mês',
        yourAccount: 'Sua conta', editProfile: 'Editar Perfil',
        cardsAndBanks: 'Cartões e contas bancárias',
        aiSettings: 'Configurações e uso da IA',
        password2FA: 'Senha e 2FA', faqContact: 'FAQ e Contato',
        themeCurrencyLang: 'Tema, moeda e idioma', logout: 'Sair',
        appearance: 'Aparência', regionLanguage: 'Região & Idioma',
        language: 'Idioma', currency: 'Moeda',
        notifications: 'Notificações', pushNotifications: 'Notificações Push',
        receiveAlerts: 'Receba alertas de orçamentos e metas',
        savePreferences: 'Salvar Preferências', saved: 'Salvo!',
        appSettings: 'Configurações do App',
        accountProtection: 'Proteção da Conta', changePassword: 'Alterar Senha',
        newPassword: 'Nova Senha', updatePassword: 'Atualizar Senha',
        updating: 'Atualizando...', twoFactorAuth: 'Autenticação de Dois Fatores (2FA)',
        addExtraLayer: 'Adicione uma camada extra de segurança.',
        authenticatorApp: 'App Autenticador',
        support: 'Suporte', helpCenter: 'Central de Ajuda',
        howCanWeHelp: 'Como podemos ajudar?',
        findAnswers: 'Encontre respostas ou entre em contato.',
        faq: 'Perguntas Frequentes', contactUs: 'Fale Conosco',
        emailSupport: 'Suporte por Email', liveChat: 'Chat ao Vivo',
        billing: 'Cobrança', addNewPayment: 'Adicionar método de pagamento',
        endingIn: 'final', expires: 'Expira',
        smartAssistant: 'Assistente Financeiro Inteligente',
        askAnything: 'Pergunte qualquer coisa',
        tellMeSpent: 'Me diga o que gastou, envie uma nota ou use o áudio.',
        messageFinbot: 'Mensagem FinBot...', listening: 'Ouvindo...',
        isTyping: 'FinBot está digitando...',
        getStarted: 'Começar', user: 'Usuário',
        transaction: 'Transação', delete: 'Excluir', cancel: 'Cancelar',
        confirm: 'Confirmar', save: 'Salvar', close: 'Fechar', back: 'Voltar',
    },
    en: {
        dashboard: 'Dashboard', transactions: 'Transactions', add: 'Add',
        budgets: 'Budgets', goals: 'Goals', reports: 'Reports',
        profile: 'Profile', preferences: 'Preferences', security: 'Security',
        help: 'Help & Support', paymentMethods: 'Payment Methods',
        investments: 'Investments', newTransaction: 'New Transaction',
        welcomeBack: 'Welcome back!', hi: 'Hi', overview: 'Overview',
        totalBalance: 'Total Balance', quickActions: 'Quick Actions',
        send: 'Send', receive: 'Receive', swap: 'Swap', payBills: 'Pay Bills',
        recentTransactions: 'Recent Transactions', seeAll: 'See All',
        cardHolder: 'Card Holder', expireDate: 'Expire Date',
        incomeBreakdown: 'Income Breakdown',
        allTransactions: 'All Transactions', searchTransactions: 'Search transactions...',
        all: 'All', noTransactionsYet: 'No transactions yet.', today: 'Today',
        addTransaction: 'Add Transaction', amount: 'Amount',
        description: 'Description', category: 'Category', date: 'Date',
        selectCategory: 'Select a category', addDescription: 'Add a description',
        creating: 'Creating...', create: 'Create',
        income: 'Income', expense: 'Expense',
        spendSmart: 'Spend Smart', noBudgets: 'No budgets setup',
        createBudget: 'Create a budget to control your spending.',
        addBudget: 'Add Budget', newBudget: 'New Budget',
        monthlyLimit: 'Monthly Limit', limitReached: 'limit reached', of: 'of',
        savings: 'Savings', lifeGoals: 'Life Goals', noGoals: 'No goals set',
        whatSavingFor: 'What are you saving for?',
        createGoal: 'Create Goal', newGoal: 'New Goal', goalName: 'Goal Name',
        targetAmount: 'Target Amount', targetDate: 'Target Date (Optional)',
        saved2: 'Saved', goal: 'Goal',
        analytics: 'Analytics', overviewReports: 'Overview Reports',
        totalIncome: 'Total Income', totalExpense: 'Total Expense',
        netBalance: 'Net Balance', expenseByCategory: 'Expense by Category',
        incomeVsExpense: 'Income vs Expense', totalSpend: 'Total Spend',
        noExpensesMonth: 'No expenses this month',
        yourAccount: 'Your account', editProfile: 'Edit Profile',
        cardsAndBanks: 'Cards & bank accounts',
        aiSettings: 'AI Settings & usage',
        password2FA: 'Password & 2FA', faqContact: 'FAQ & Contact',
        themeCurrencyLang: 'Theme, currency & language', logout: 'Logout',
        appearance: 'Appearance', regionLanguage: 'Region & Language',
        language: 'Language', currency: 'Currency',
        notifications: 'Notifications', pushNotifications: 'Push Notifications',
        receiveAlerts: 'Receive alerts for budgets and goals',
        savePreferences: 'Save Preferences', saved: 'Saved!',
        appSettings: 'App Settings',
        accountProtection: 'Account Protection', changePassword: 'Change Password',
        newPassword: 'New Password', updatePassword: 'Update Password',
        updating: 'Updating...', twoFactorAuth: 'Two-Factor Authentication (2FA)',
        addExtraLayer: 'Add an extra layer of security.',
        authenticatorApp: 'Authenticator App',
        support: 'Support', helpCenter: 'Help Center',
        howCanWeHelp: 'How can we help?',
        findAnswers: 'Find answers or get in touch.',
        faq: 'Frequently Asked Questions', contactUs: 'Contact Us',
        emailSupport: 'Email Support', liveChat: 'Live Chat',
        billing: 'Billing', addNewPayment: 'Add new payment method',
        endingIn: 'ending in', expires: 'Expires',
        smartAssistant: 'Smart Financial Assistant',
        askAnything: 'Ask anything',
        tellMeSpent: 'Tell me what you spent, upload an invoice, or use audio.',
        messageFinbot: 'Message FinBot...', listening: 'Listening...',
        isTyping: 'FinBot is typing...',
        getStarted: 'Get Started', user: 'User',
        transaction: 'Transaction', delete: 'Delete', cancel: 'Cancel',
        confirm: 'Confirm', save: 'Save', close: 'Close', back: 'Back',
    },
    es: {
        dashboard: 'Panel', transactions: 'Transacciones', add: 'Agregar',
        budgets: 'Presupuestos', goals: 'Metas', reports: 'Informes',
        profile: 'Perfil', preferences: 'Preferencias', security: 'Seguridad',
        help: 'Ayuda & Soporte', paymentMethods: 'Métodos de Pago',
        investments: 'Inversiones', newTransaction: 'Nueva Transacción',
        welcomeBack: '¡Bienvenido!', hi: 'Hola', overview: 'Resumen',
        totalBalance: 'Saldo Total', quickActions: 'Acciones Rápidas',
        send: 'Enviar', receive: 'Recibir', swap: 'Cambiar', payBills: 'Pagar Cuentas',
        recentTransactions: 'Transacciones Recientes', seeAll: 'Ver Todo',
        cardHolder: 'Titular', expireDate: 'Vencimiento',
        incomeBreakdown: 'Análisis de Ingresos',
        allTransactions: 'Todas las Transacciones', searchTransactions: 'Buscar transacciones...',
        all: 'Todos', noTransactionsYet: 'Sin transacciones aún.', today: 'Hoy',
        addTransaction: 'Agregar Transacción', amount: 'Monto',
        description: 'Descripción', category: 'Categoría', date: 'Fecha',
        selectCategory: 'Seleccione categoría', addDescription: 'Agregue descripción',
        creating: 'Creando...', create: 'Crear',
        income: 'Ingreso', expense: 'Gasto',
        spendSmart: 'Gasta Inteligente', noBudgets: 'Sin presupuestos',
        createBudget: 'Crea un presupuesto para controlar tus gastos.',
        addBudget: 'Agregar Presupuesto', newBudget: 'Nuevo Presupuesto',
        monthlyLimit: 'Límite Mensual', limitReached: 'del límite alcanzado', of: 'de',
        savings: 'Ahorros', lifeGoals: 'Metas de Vida', noGoals: 'Sin metas',
        whatSavingFor: '¿Para qué estás ahorrando?',
        createGoal: 'Crear Meta', newGoal: 'Nueva Meta', goalName: 'Nombre de la Meta',
        targetAmount: 'Monto Objetivo', targetDate: 'Fecha Objetivo (Opcional)',
        saved2: 'Ahorrado', goal: 'Meta',
        analytics: 'Analíticas', overviewReports: 'Informes Generales',
        totalIncome: 'Ingreso Total', totalExpense: 'Gasto Total',
        netBalance: 'Saldo Neto', expenseByCategory: 'Gastos por Categoría',
        incomeVsExpense: 'Ingresos vs Gastos', totalSpend: 'Total Gastado',
        noExpensesMonth: 'Sin gastos este mes',
        yourAccount: 'Tu cuenta', editProfile: 'Editar Perfil',
        cardsAndBanks: 'Tarjetas y cuentas bancarias',
        aiSettings: 'Configuración y uso de IA',
        password2FA: 'Contraseña y 2FA', faqContact: 'FAQ y Contacto',
        themeCurrencyLang: 'Tema, moneda e idioma', logout: 'Cerrar sesión',
        appearance: 'Apariencia', regionLanguage: 'Región & Idioma',
        language: 'Idioma', currency: 'Moneda',
        notifications: 'Notificaciones', pushNotifications: 'Notificaciones Push',
        receiveAlerts: 'Recibir alertas de presupuestos y metas',
        savePreferences: 'Guardar Preferencias', saved: '¡Guardado!',
        appSettings: 'Ajustes de la App',
        accountProtection: 'Protección de Cuenta', changePassword: 'Cambiar Contraseña',
        newPassword: 'Nueva Contraseña', updatePassword: 'Actualizar Contraseña',
        updating: 'Actualizando...', twoFactorAuth: 'Autenticación de Dos Factores (2FA)',
        addExtraLayer: 'Agrega una capa extra de seguridad.',
        authenticatorApp: 'App Autenticador',
        support: 'Soporte', helpCenter: 'Centro de Ayuda',
        howCanWeHelp: '¿Cómo podemos ayudar?',
        findAnswers: 'Encuentra respuestas o contacta a nuestro equipo.',
        faq: 'Preguntas Frecuentes', contactUs: 'Contáctanos',
        emailSupport: 'Soporte por Email', liveChat: 'Chat en Vivo',
        billing: 'Facturación', addNewPayment: 'Agregar método de pago',
        endingIn: 'terminada en', expires: 'Expira',
        smartAssistant: 'Asistente Financiero Inteligente',
        askAnything: 'Pregunta lo que sea',
        tellMeSpent: 'Dime qué gastaste, sube una factura o usa el audio.',
        messageFinbot: 'Mensaje FinBot...', listening: 'Escuchando...',
        isTyping: 'FinBot está escribiendo...',
        getStarted: 'Comenzar', user: 'Usuario',
        transaction: 'Transacción', delete: 'Eliminar', cancel: 'Cancelar',
        confirm: 'Confirmar', save: 'Guardar', close: 'Cerrar', back: 'Volver',
    },
};

export const t = (key) => {
    const lang = useStore.getState().language || 'pt-BR';
    return translations[lang]?.[key] || translations['en']?.[key] || key;
};
